name: Update Filters
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Run update-filters.sh
        run: |
          chmod +x ruleset_converter update-filters.sh
          ./update-filters.sh

      - name: Generate date
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Commit filters
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'filters.dat'
          default_author: github_actions
          message: 'Update filters: ${{ env.DATE }}'
          push: true

      - name: Release filter lists
        uses: softprops/action-gh-release@v1
        with:
          files: filters.dat
          name: Filterlist ${{ env.DATE }}
          tag_name: ${{ env.DATE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
