name: Update ruleset_converter
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ruleset_converter
        run: |
          wget https://github.com/bromite/bromite/releases/latest/download/ruleset_converter

      - name: Generate date
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Commit ruleset_converter
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'ruleset_converter'
          default_author: user_info
          message: 'Update ruleset_converter: ${{ env.DATE }}'
          push: true

  
